'use client';

import { useState } from 'react';
import { TopBar } from '../TopBar';
import { Button } from '../Button';
import { Icon } from '../Icon';
const DEFAULT_SETTINGS = {
  apiKeys: { apollo: '', apify: '', openai: '' },
  safetyCaps: { dailyEmailLimit: 50, budgetLimit: 100 },
  behavior: { autoEnrich: true, autoGenerateDrafts: false, requireApproval: true },
};

export function SettingsPage() {
  const [settings, setSettings] = useState(DEFAULT_SETTINGS);

  return (
    <>
      <TopBar
        title="Settings"
        showSearch={false}
        actions={
          <Button variant="primary" icon="save">
            Save Changes
          </Button>
        }
      />
      <div style={{ flex: 1, overflow: 'auto', padding: 24 }}>
        <div style={{ maxWidth: 800 }}>
          <div
            style={{
              background: 'var(--bg-app)',
              border: '1px solid var(--border-card)',
              borderRadius: 8,
              padding: 20,
              marginBottom: 16,
            }}
          >
            <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
              <Icon name="key" size={18} />
              API Credentials
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div>
                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, marginBottom: 6 }}>Contact data key</label>
                <input
                  type="password"
                  value={settings?.apiKeys.apollo || ''}
                  style={{
                    width: '100%',
                    height: 36,
                    padding: '0 12px',
                    border: '1px solid var(--border-card)',
                    borderRadius: 6,
                    fontSize: 13,
                    fontFamily: 'var(--font-mono)',
                    background: 'var(--bg-app)',
                    color: 'var(--fg-primary)',
                  }}
                />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, marginBottom: 6 }}>Profile data key</label>
                <input
                  type="password"
                  value={settings?.apiKeys.apify || ''}
                  style={{
                    width: '100%',
                    height: 36,
                    padding: '0 12px',
                    border: '1px solid var(--border-card)',
                    borderRadius: 6,
                    fontSize: 13,
                    fontFamily: 'var(--font-mono)',
                    background: 'var(--bg-app)',
                    color: 'var(--fg-primary)',
                  }}
                />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, marginBottom: 6 }}>AI model key</label>
                <input
                  type="password"
                  value={settings?.apiKeys.openai || ''}
                  style={{
                    width: '100%',
                    height: 36,
                    padding: '0 12px',
                    border: '1px solid var(--border-card)',
                    borderRadius: 6,
                    fontSize: 13,
                    fontFamily: 'var(--font-mono)',
                    background: 'var(--bg-app)',
                    color: 'var(--fg-primary)',
                  }}
                />
              </div>
            </div>
          </div>

          <div
            style={{
              background: 'var(--bg-app)',
              border: '1px solid var(--border-card)',
              borderRadius: 8,
              padding: 20,
              marginBottom: 16,
            }}
          >
            <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
              <Icon name="shield" size={18} />
              Safety Caps
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div>
                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, marginBottom: 6 }}>
                  Daily Email Limit
                </label>
                <input
                  type="number"
                  value={settings?.safetyCaps.dailyEmailLimit || 0}
                  style={{
                    width: '100%',
                    height: 36,
                    padding: '0 12px',
                    border: '1px solid var(--border-card)',
                    borderRadius: 6,
                    fontSize: 13,
                    background: 'var(--bg-app)',
                    color: 'var(--fg-primary)',
                  }}
                />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, marginBottom: 6 }}>
                  Budget Limit ($)
                </label>
                <input
                  type="number"
                  value={settings?.safetyCaps.budgetLimit || 0}
                  style={{
                    width: '100%',
                    height: 36,
                    padding: '0 12px',
                    border: '1px solid var(--border-card)',
                    borderRadius: 6,
                    fontSize: 13,
                    background: 'var(--bg-app)',
                    color: 'var(--fg-primary)',
                  }}
                />
              </div>
            </div>
          </div>

          <div
            style={{
              background: 'var(--bg-app)',
              border: '1px solid var(--border-card)',
              borderRadius: 8,
              padding: 20,
            }}
          >
            <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
              <Icon name="sliders" size={18} />
              Behavior
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                <input type="checkbox" checked={settings?.behavior.autoEnrich} />
                <span style={{ fontSize: 13 }}>Auto-enrich new prospects</span>
              </label>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                <input type="checkbox" checked={settings?.behavior.autoGenerateDrafts} />
                <span style={{ fontSize: 13 }}>Auto-generate email drafts</span>
              </label>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                <input type="checkbox" checked={settings?.behavior.requireApproval} />
                <span style={{ fontSize: 13 }}>Require approval before sending</span>
              </label>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
