// ──────────────────────────────────────────────────────────────────
// Recruitr — Type Definitions
// ──────────────────────────────────────────────────────────────────

export type ProspectStatus =
  | 'NEW'
  | 'VALIDATED'
  | 'ENRICHED'
  | 'READY_TO_SEND'
  | 'SENT'
  | 'FOLLOW_UP_F1'
  | 'FOLLOW_UP_F2'
  | 'FOLLOW_UP_F3'
  | 'REPLIED'
  | 'NEEDS_REVIEW'
  | 'DEAD_LETTER'
  | 'DISCARDED';

export type StatusTone = 'neutral' | 'amber' | 'warning' | 'info' | 'success' | 'purple' | 'danger';

export interface Prospect {
  id: string;
  businessName: string;
  category: string;
  city: string;
  state: string;
  country: string;
  status: ProspectStatus;
  hasEmail: boolean;
  rating: number;
  reviewCount: number;
  lastUpdated: string;
  address: string | null;
  phone: string | null;
  website: string | null;
  contactName: string | null;
  contactEmail: string | null;
  contactTitle: string | null;
  linkedinUrl: string | null;
  companySize: string | null;
  industry: string | null;
  timeline: TimelineEvent[];
}

export interface TimelineEvent {
  state: string;
  timestamp: string;
  actor: string;
  note?: string;
}

export interface Company {
  id: string;
  name: string;
  domain: string | null;
  industry: string;
  size: string;
  location: string;
  prospectCount: number;
  lastUpdated: string;
}

export interface ICPConfig {
  id: string;
  name: string;
  description: string;
  criteria: ICPCriteria;
  status: 'ACTIVE' | 'PAUSED' | 'DRAFT';
  createdAt: string;
  updatedAt: string;
}

export interface ICPCriteria {
  industries: string[];
  titles: string[];
  companySize: string[];
  locations: string[];
  keywords: string[];
}

export interface Run {
  id: string;
  icpId: string;
  status: 'RUNNING' | 'COMPLETED' | 'FAILED' | 'PAUSED';
  startedAt: string;
  completedAt: string | null;
  prospectsFound: number;
  prospectsEnriched: number;
  budget: number;
  spent: number;
  progress: number;
}

export interface RunDetail extends Run {
  config: ICPConfig;
  logs: LogEntry[];
  metrics: RunMetrics;
}

export interface LogEntry {
  id: string;
  timestamp: string;
  level: 'INFO' | 'WARN' | 'ERROR';
  message: string;
  metadata?: Record<string, any>;
}

export interface RunMetrics {
  totalSearched: number;
  newProspects: number;
  duplicates: number;
  enriched: number;
  errors: number;
  avgEnrichmentTime: number;
}

export interface DashboardMetrics {
  totalProspects: number;
  activeRuns: number;
  emailsSentToday: number;
  replyRate: number;
  weeklyTrend: number[];
}

export interface OutreachTemplate {
  id: string;
  name: string;
  subject: string;
  body: string;
  variables: string[];
  createdAt: string;
}

export interface Integration {
  id: string;
  name: string;
  type: 'EMAIL' | 'CRM' | 'ENRICHMENT' | 'DISCOVERY';
  status: 'CONNECTED' | 'DISCONNECTED' | 'ERROR';
  lastSync: string | null;
  config: Record<string, any>;
}

export interface Settings {
  apiKeys: {
    apollo: string | null;
    apify: string | null;
    openai: string | null;
  };
  safetyCaps: {
    dailyEmailLimit: number;
    budgetLimit: number;
    enrichmentConcurrency: number;
  };
  behavior: {
    autoEnrich: boolean;
    autoGenerateDrafts: boolean;
    requireApproval: boolean;
  };
  senderIdentity: {
    name: string;
    email: string;
    signature: string;
  };
}
